### ISSUE TITLE
Way to make a package as "don't build"

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [pelson/Obvious-CI#10]
Using the build a whe dit build script, it would be nice to have a way to mark a package as "don't build" -- probably on a per-platfrom basis.

This would be very helpful for testing / debugging.

Also -- there may well be some packages that you only want on some platforms -- or at least temporarily, as they don't build on all of them. Or is there a way to do that already?

**Comment by pelson** [comment]
> Or is there a way to do that already?

No. It also links quite well to #1, but is clearly a different beast. I'm not sure the best way to resolve this. Part of me is wondering if meta packages is the way to go on this...

**Comment by ChrisBarker-NOAA** [comment]
meta-packages could be good. 

I have a couple use cases. The first was during testing/debugging -- I had a few packages that wouldn't' build, and the whole system stops because of it. So what I did was move the entire directory out of the repo, and then put it back when I wanted to build it -- pretty kludgy.

So I thought it would be nice to essentially "comment out" a package. Maybe put something in the meta.yaml that only obvious-ci would bother with?

**Comment by pelson** [comment]
I've just put a PR in to conda-build which would give us the metadata to do this within ObviousCI: https://github.com/conda/conda-build/pull/566

**Comment by ChrisBarker-NOAA** [comment]
Good idea, thanks.

Sent from my iPhone

On Aug 31, 2015, at 3:35 AM, Phil Elson <notifications@github.com> wrote:

I've just put a PR in to conda-build which would give us the metadata to do
this within ObviousCI: conda/conda-build#566
<https://github.com/conda/conda-build/pull/566>

—
Reply to this email directly or view it on GitHub
<https://github.com/pelson/Obvious-CI/issues/10#issuecomment-136288315>.

**Comment by pelson** [comment]
Closed with #40.
