### ISSUE TITLE
How to specify the build matrix???

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [pelson/Obvious-CI#33]
I've just upgraded to the latest master and found that obvious is now trying to build packages for a whole pile of python versions -- cool!

However, I don't actually want all those -- in this case, only py2.7

how can I tell it to chill out and only do that ;-)

By the way -- very cool tool. but it really needs some docs -- or am I missing something?

**Comment by ocefpaf** [comment]
I think that,

`obvci_conda_build_dir.py <directory> <channel> --channel main --build-condition "python >=2.7,<3"`

should do the trick.

**Comment by ChrisBarker-NOAA** [comment]
Beautiful -- that's working perfectly.

**Comment by pelson** [comment]
> By the way -- very cool tool. but it really needs some docs

Agreed. Nothing yet, but I think it is getting time to start.

Thanks for the feedback @ChrisBarker-NOAA

**Comment by pelson** [comment]
P.S. the default build matrix is defined in https://github.com/pelson/Obvious-CI/blob/master/obvci/conda_tools/build_directory.py#L187.

**Comment by ChrisBarker-NOAA** [comment]
great, thanks!
