### ISSUE TITLE
Latest Obvious-CI version is trying to build against all python versions

### ISSUE THREAD

**Issue by ocefpaf** [pelson/Obvious-CI#39]
In our recipe for [`optcomplete`](https://github.com/ioos/conda-recipes/blob/master/optcomplete/meta.yaml#L15) we are limiting the python version with  >=2.7,<3, but the latest version of obvious-ci is trying to build against Python 3 regardless.
(See https://ci.appveyor.com/project/comtbot/conda-recipes/build/1.0.1218/job/9cc54i7pmjrk90fx.)

Is that planned or is this an unexpected side effect from #37?

**Update:** I forgot to mention that this happens only on Windows.  (On Windows I do set the `CONDA_PY` version in the build matrix.)

**Comment by ocefpaf** [comment]
I forgot to mention that this happens only on Windows.  (On Windows I do set the `CONDA_PY` version in the build matrix.)

**Comment by ocefpaf** [comment]
After reading the changes on `special_case_version_matrix` I believe that this is happening because of this modification:

```diff
-    requirements = meta.get_value('requirements/build', [])
+    requirements = meta.get_value('requirements/run', [])
```

If that is the right way to parse the requirements for the build matrix then we should start adding `>=2.7,<3` to both `build` and `run` `requirements`. However, that will result in packages without the `py` build string.

My workaround is to manually construct the build string.  (See https://github.com/ioos/conda-recipes/pull/538.)

**Comment by pelson** [comment]
No not intentional. :disappointed:

**Comment by mwcraig** [comment]
FYI, in current (0.5.1) obvious-ci and current (1.18.1) conda-build you can specify both the range of python versions supported and that python should be included in the build string like this:

```
- build
  - python x.x # ensure python version is pinned in build
  - python >2.6,<3

-run
  - python x.x # ensure python is part of build id...yes, you currently need this in BOTH
  - python >2.6,<3 # not actually NECESSARY, but does no harm
```

**Comment by mwcraig** [comment]
Just to add a bit more to this, the same trick does not work with numpy. 

And the trick above requires the requirements be listed in the order above. Basically it works (I think) because obvious-ci  only uses the [last requirement listed](https://github.com/pelson/Obvious-CI/blob/1d0d806e7d7e184bc0b5e66cac2486d8f7e432fe/obvci/conda_tools/from_conda_manifest_core_vn_matrix.py#L123) but conda-build recognizes the x.x and adds `py` to the build string.

(Sorry I've ended up using this issue as a notebook...)

**Comment by pelson** [comment]
> (Sorry I've ended up using this issue as a notebook...)

No problem. Useful to have your notes!
