### ISSUE TITLE
Use latest Miniconda by default

### ISSUE THREAD

**Issue by Juanlu001** [pelson/Obvious-CI#58]
conda has some open issues regarding non-ASCII text in Python 2:

https://github.com/conda/conda/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+unicode+OR+ascii

I doubt the developers will put much effort in fixing them because everything works as expected on Python 3. Would you consider bootstraping Miniconda3 instead?

(Original issue discovered at https://github.com/conda-forge/staged-recipes/pull/214)

**Comment by jakirkham** [comment]
Thanks. :smile: Could we also have that conda issue you found here too?

**Comment by jakirkham** [comment]
Oh, this might be better on [staged-recipes]( https://github.com/conda-forge/staged-recipes ) because that is where Miniconda gets installed.

**Comment by Juanlu001** [comment]
We can close this one if you wish and continue conversation there. Whatever you feel more appropriate.

**Comment by jakirkham** [comment]
That sounds like a good idea. Let's do that. Thanks. :smile:

**Comment by Juanlu001** [comment]
On second thought: while there's the issue of using Miniconda3 on staged-recipes, there's also the question about changing the _default_ Miniconda version for Obvious-CI, which is selected here:

https://github.com/pelson/Obvious-CI/blob/e671ef2/bootstrap-obvious-ci-and-miniconda.py#L49

So I am reopening this and leaving it as a question to the maintainers :)

**Comment by pelson** [comment]
:+1: completely. Let's get with the times! :smile:

**Comment by pelson** [comment]
Looking a little deeper, we just need to update the appropriate scripts in staged-recipes. The bootstrap script here doesn't pre-determine 2 or 3. I've opened a PR there: https://github.com/conda-forge/staged-recipes/pull/217

I'm not sure there is anything to be done in this repo?

**Comment by jakirkham** [comment]
So, should this be closed then?
